package com.evram.androidstudio

import android.app.Activity
import android.app.AlertDialog
import android.content.Intent
import android.graphics.Color
import android.graphics.Typeface
import android.net.Uri
import android.os.Bundle
import android.text.Editable
import android.text.TextWatcher
import android.view.Gravity
import android.widget.*
import androidx.documentfile.provider.DocumentFile
import java.io.File

class MainActivity : Activity() {
    private val bg=Color.rgb(30,30,30); private val panel=Color.rgb(37,37,38); private val panel2=Color.rgb(45,45,48); private val fgColor=Color.rgb(230,230,230); private val muted=Color.rgb(150,150,150)
    private fun dp(v:Int)=(v*resources.displayMetrics.density).toInt()
    private fun tv(s:String,size:Float=14f,c:Int=fgColor)=TextView(this).apply{text=s;textSize=size;setTextColor(c);gravity=Gravity.CENTER_VERTICAL}
    private fun btn(s:String)=Button(this).apply{text=s;textSize=12f;isAllCaps=false;setTextColor(fgColor);minHeight=dp(40)}
    private lateinit var status:TextView
    private var currentFile:File?=null
    private var editor:EditText?=null
    private var dirty=false
    private val pending=mutableMapOf<String,String>()
    private var exportProject:String?=null

    override fun onCreate(b:Bundle?){super.onCreate(b);showManager()}
    private fun prefs()=getSharedPreferences("projects",MODE_PRIVATE)
    private fun projectDir(name:String)=File(filesDir,"projects/$name")

    private fun showManager(){
        currentFile=null;editor=null;dirty=false
        val root=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setBackgroundColor(bg)}
        val bar=LinearLayout(this).apply{orientation=LinearLayout.HORIZONTAL;gravity=Gravity.CENTER_VERTICAL;setPadding(dp(16),0,dp(10),0);setBackgroundColor(panel2)}
        bar.addView(tv("AS4A",18f).apply{setTypeface(null,Typeface.BOLD)},LinearLayout.LayoutParams(dp(65),-1))
        bar.addView(tv("Project Manager",16f),LinearLayout.LayoutParams(0,-1,1f))
        val storage=btn("Storage");bar.addView(storage,LinearLayout.LayoutParams(dp(88),dp(44)));storage.setOnClickListener{showStorageDialog()}
        val settings=btn("⚙");bar.addView(settings,LinearLayout.LayoutParams(dp(55),dp(44)));settings.setOnClickListener{showSettings()}
        root.addView(bar,LinearLayout.LayoutParams(-1,dp(56)))
        val content=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(dp(24),dp(24),dp(24),dp(24))}
        content.addView(tv("Projects",22f),LinearLayout.LayoutParams(-1,dp(50)));content.addView(tv("Choose a project to open its IDE workspace.",14f,muted),LinearLayout.LayoutParams(-1,dp(36)))
        val list=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL};val names=prefs().getStringSet("names",emptySet())!!.toMutableSet();names.sorted().forEach{addProjectRow(list,it)}
        val newBtn=btn("＋  New Project");newBtn.setOnClickListener{createProject(list,names)};content.addView(newBtn,LinearLayout.LayoutParams(-1,dp(52)))
        val scroll=ScrollView(this);scroll.addView(list);content.addView(scroll,LinearLayout.LayoutParams(-1,0,1f));root.addView(content,LinearLayout.LayoutParams(-1,0,1f))
        status=tv("  Ready",12f,muted);status.setBackgroundColor(panel2);root.addView(status,LinearLayout.LayoutParams(-1,dp(30)));setContentView(root)
    }

    private fun showSettings(){AlertDialog.Builder(this).setTitle("Settings").setItems(arrayOf("Editor settings","Project defaults","Build settings","About AS4A")){_,which->Toast.makeText(this,arrayOf("Editor settings coming soon","Project defaults coming soon","Build engine coming soon","Android Studio for Android")[which],Toast.LENGTH_SHORT).show()}.show()}

    private fun showStorageDialog(){
        AlertDialog.Builder(this).setTitle("Storage Access Framework").setMessage("Choose a folder from Android's file picker. AS4A can import projects from that folder or export a project to it. Android keeps the permission so you can use the folder again.")
            .setItems(arrayOf("Import project from storage","Export a project to storage","Choose workspace folder")){_,which->if(which==0)pickImportFolder()else if(which==1)chooseProjectForExport()else pickWorkspaceFolder()}.show()
    }

    private fun pickWorkspaceFolder(){startActivityForResult(Intent(Intent.ACTION_OPEN_DOCUMENT_TREE).addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION or Intent.FLAG_GRANT_WRITE_URI_PERMISSION or Intent.FLAG_GRANT_PERSISTABLE_URI_PERMISSION),100)}
    private fun pickImportFolder(){startActivityForResult(Intent(Intent.ACTION_OPEN_DOCUMENT_TREE).addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION or Intent.FLAG_GRANT_PERSISTABLE_URI_PERMISSION),101)}
    private fun chooseProjectForExport(){val names=prefs().getStringSet("names",emptySet())!!.sorted();if(names.isEmpty()){Toast.makeText(this,"Create a project first",Toast.LENGTH_SHORT).show();return};AlertDialog.Builder(this).setTitle("Export project").setItems(names.toTypedArray()){_,which->exportProject=names[which];startActivityForResult(Intent(Intent.ACTION_OPEN_DOCUMENT_TREE).addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION or Intent.FLAG_GRANT_WRITE_URI_PERMISSION or Intent.FLAG_GRANT_PERSISTABLE_URI_PERMISSION),102)}.show()}

    override fun onActivityResult(requestCode:Int,resultCode:Int,data:Intent?){super.onActivityResult(requestCode,resultCode,data);if(resultCode!=RESULT_OK||data?.data==null)return;val uri=data.data!!;try{contentResolver.takePersistableUriPermission(uri,data.flags and (Intent.FLAG_GRANT_READ_URI_PERMISSION or Intent.FLAG_GRANT_WRITE_URI_PERMISSION))}catch(_:Exception){};when(requestCode){100->prefs().edit().putString("workspaceUri",uri.toString()).apply().also{Toast.makeText(this,"Workspace folder connected",Toast.LENGTH_SHORT).show()};101->importFromTree(uri);102->exportToTree(uri,exportProject)}}

    private fun importFromTree(uri:Uri){val picked=DocumentFile.fromTreeUri(this,uri)?:return;val name=(picked.name?:"ImportedProject").replace("/","_");val safe=if(name.isBlank())"ImportedProject" else name;val names=prefs().getStringSet("names",emptySet())!!.toMutableSet();if(names.contains(safe)){Toast.makeText(this,"Project already exists: $safe",Toast.LENGTH_SHORT).show();return};val dest=projectDir(safe);dest.mkdirs();copyDocumentTree(picked,dest);names.add(safe);prefs().edit().putStringSet("names",names).putString("last",safe).apply();Toast.makeText(this,"Imported $safe",Toast.LENGTH_SHORT).show();showManager()}

    private fun copyDocumentTree(source:DocumentFile,dest:File){if(source.isDirectory){dest.mkdirs();source.listFiles().forEach{child->copyDocumentTree(child,File(dest,child.name?:("item_"+System.nanoTime())))}}else{try{dest.parentFile?.mkdirs();contentResolver.openInputStream(source.uri)?.use{input->dest.outputStream().use{output->input.copyTo(output)}}}catch(e:Exception){Toast.makeText(this,"Could not copy ${source.name}",Toast.LENGTH_SHORT).show()}}}

    private fun exportToTree(uri:Uri,project:String?){if(project==null)return;val parent=DocumentFile.fromTreeUri(this,uri)?:return;val root=projectDir(project);val target=parent.findFile(project)?.takeIf{it.isDirectory}?:parent.createDirectory(project);if(target==null){Toast.makeText(this,"Could not create export folder",Toast.LENGTH_SHORT).show();return};copyFileTreeToDocument(root,target);Toast.makeText(this,"Exported $project",Toast.LENGTH_SHORT).show();exportProject=null}
    private fun copyFileTreeToDocument(source:File,target:DocumentFile){source.listFiles()?.forEach{f->if(f.isDirectory){val d=target.findFile(f.name)?.takeIf{it.isDirectory}?:target.createDirectory(f.name);if(d!=null)copyFileTreeToDocument(f,d)}else{try{target.findFile(f.name)?.delete();val d=target.createFile("application/octet-stream",f.name);if(d!=null)f.inputStream().use{input->contentResolver.openOutputStream(d.uri)?.use{output->input.copyTo(output)}}}catch(_:Exception){}}}}

    private fun createProject(list:LinearLayout,names:MutableSet<String>){val input=EditText(this).apply{hint="Project name"};val pkg=EditText(this).apply{hint="Package name (optional)"};val box=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(dp(16),0,dp(16),0)};box.addView(input);box.addView(pkg);AlertDialog.Builder(this).setTitle("Create Project").setView(box).setNegativeButton("Cancel",null).setPositiveButton("Create"){_,_->val n=input.text.toString().trim().ifEmpty{"MyProject"};if(names.add(n)){val p=pkg.text.toString().trim().ifEmpty{"com.example.${n.lowercase().replace(Regex("[^a-z0-9]"),"")}"};prefs().edit().putStringSet("names",names).putString("last",n).apply();val dir=projectDir(n);dir.mkdirs();createStarterFiles(dir,n,p);addProjectRow(list,n);openWorkspace(n)}else Toast.makeText(this,"Project already exists",Toast.LENGTH_SHORT).show()}.show()}
    private fun createStarterFiles(dir:File,name:String,pkg:String){val main=File(dir,"app/src/main");File(main,"java/${pkg.replace('.','/')}").mkdirs();File(main,"res").mkdirs();writeIfMissing(File(dir,"project.properties"),"name=$name\npackage=$pkg\nminSdk=26\ntargetSdk=35\ncompileSdk=35\ntemplate=Empty Activity\n");writeIfMissing(File(dir,"settings.gradle.kts"),"rootProject.name = \"$name\"\ninclude(\":app\")\n");writeIfMissing(File(dir,"build.gradle.kts"),"// Root Gradle build file\n");writeIfMissing(File(dir,"app/build.gradle.kts"),"plugins {\n    id(\"com.android.application\")\n    id(\"org.jetbrains.kotlin.android\")\n}\n\nandroid {\n    namespace = \"$pkg\"\n    compileSdk = 35\n}\n");writeIfMissing(File(main,"AndroidManifest.xml"),"<?xml version=\"1.0\" encoding=\"utf-8\"?>\n<manifest xmlns:android=\"http://schemas.android.com/apk/res/android\">\n    <application android:label=\"$name\" />\n</manifest>\n");writeIfMissing(File(main,"java/${pkg.replace('.','/')}/MainActivity.kt"),"package $pkg\n\nclass MainActivity {\n    // Start building your app here.\n}\n");writeIfMissing(File(dir,"README.md"),"# $name\n\nCreated with Android Studio for Android.\n")}
    private fun writeIfMissing(f:File,s:String){if(!f.exists()){f.parentFile?.mkdirs();f.writeText(s)}}

    private fun addProjectRow(list:LinearLayout,n:String){val row=LinearLayout(this).apply{orientation=LinearLayout.HORIZONTAL;gravity=Gravity.CENTER_VERTICAL;setPadding(dp(12),dp(4),dp(8),dp(4));setBackgroundColor(panel)};row.addView(tv("📁  $n",15f),LinearLayout.LayoutParams(0,dp(58),1f));val settings=btn("⚙");val del=btn("Delete");val export=btn("Export");row.addView(settings,LinearLayout.LayoutParams(dp(52),dp(44)));row.addView(export,LinearLayout.LayoutParams(dp(70),dp(44)));row.addView(del,LinearLayout.LayoutParams(dp(76),dp(44)));row.setOnClickListener{openWorkspace(n)};settings.setOnClickListener{showProjectSettings(n)};export.setOnClickListener{exportProject=n;startActivityForResult(Intent(Intent.ACTION_OPEN_DOCUMENT_TREE).addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION or Intent.FLAG_GRANT_WRITE_URI_PERMISSION or Intent.FLAG_GRANT_PERSISTABLE_URI_PERMISSION),102)};del.setOnClickListener{deleteProject(list,row,n)};row.setOnLongClickListener{showProjectSettings(n);true};list.addView(row,LinearLayout.LayoutParams(-1,dp(66)).apply{setMargins(0,dp(6),0,0)})}
    private fun deleteProject(list:LinearLayout,row:LinearLayout,n:String){AlertDialog.Builder(this).setTitle("Delete Project?").setMessage("Delete $n and all of its files?").setNegativeButton("Cancel",null).setPositiveButton("Delete"){_,_->prefs().edit().putStringSet("names",prefs().getStringSet("names",emptySet())!!.filter{it!=n}.toSet()).apply();projectDir(n).deleteRecursively();list.removeView(row);status.text="  Deleted $n"}.show()}

    private fun showProjectSettings(name:String){val f=projectDir(name).resolve("project.properties");val props=f.takeIf{it.exists()}?.readLines()?.mapNotNull{it.split("=",limit=2).takeIf{p->p.size==2}?.let{p->p[0] to p[1]}}?.toMap()?:emptyMap();val box=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(dp(16),0,dp(16),0)};val fields=linkedMapOf<String,EditText>();listOf("name","package","minSdk","targetSdk","compileSdk","template").forEach{key->val e=EditText(this).apply{hint=key;setText(props[key]?:(if(key=="name")name else ""))};fields[key]=e;box.addView(e)};AlertDialog.Builder(this).setTitle("Project Settings").setView(box).setNegativeButton("Cancel",null).setPositiveButton("Save"){_,_->f.parentFile?.mkdirs();f.writeText(fields.entries.joinToString("\n"){(k,e)->"$k=${e.text}"}+"\n");status.text="  Saved settings for $name"}.show()}

    private fun openWorkspace(projectName:String){prefs().edit().putString("last",projectName).apply();currentFile=null;dirty=false;pending.clear();val root=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setBackgroundColor(bg)};val bar=LinearLayout(this).apply{orientation=LinearLayout.HORIZONTAL;gravity=Gravity.CENTER_VERTICAL;setBackgroundColor(panel2)};val back=btn("← Projects");bar.addView(back,LinearLayout.LayoutParams(dp(105),dp(48)));bar.addView(tv("  📁 $projectName",16f),LinearLayout.LayoutParams(0,dp(48),1f));val run=btn("▶ Run");bar.addView(run,LinearLayout.LayoutParams(dp(75),dp(48)));run.setOnClickListener{Toast.makeText(this,"Build engine coming later",Toast.LENGTH_SHORT).show()};root.addView(bar)
        val body=LinearLayout(this).apply{orientation=LinearLayout.HORIZONTAL};val tree=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setBackgroundColor(panel);setPadding(dp(8),dp(8),dp(8),dp(8))};val header=LinearLayout(this).apply{orientation=LinearLayout.HORIZONTAL;gravity=Gravity.CENTER_VERTICAL};header.addView(tv("PROJECT",12f,muted),LinearLayout.LayoutParams(0,dp(42),1f));val add=btn("＋");header.addView(add,LinearLayout.LayoutParams(dp(50),dp(42)));val refresh=btn("↻");header.addView(refresh,LinearLayout.LayoutParams(dp(50),dp(42)));tree.addView(header);val dir=projectDir(projectName);dir.mkdirs();renderTree(tree,dir,"",projectName)
        val area=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL};val tab=tv("  No file selected",13f);tab.setBackgroundColor(panel2);area.addView(tab,LinearLayout.LayoutParams(-1,dp(42)));editor=EditText(this).apply{setTextColor(fgColor);setHintTextColor(muted);textSize=14f;typeface=Typeface.MONOSPACE;gravity=Gravity.TOP or Gravity.START;setPadding(dp(16),dp(12),dp(16),dp(12));setBackgroundColor(bg);hint="Select a file to edit";isSingleLine=false};editor?.addTextChangedListener(object:TextWatcher{override fun beforeTextChanged(s:CharSequence?,st:Int,c:Int,a:Int){};override fun onTextChanged(s:CharSequence?,st:Int,b:Int,c:Int){if(currentFile!=null){dirty=true;tab.text="  ${currentFile!!.name} *"}};override fun afterTextChanged(e:Editable?) {}});area.addView(editor,LinearLayout.LayoutParams(-1,0,1f));val save=btn("💾 Save");save.setOnClickListener{saveCurrent(tab)};area.addView(save,LinearLayout.LayoutParams(-1,dp(46)));body.addView(ScrollView(this).apply{addView(tree)},LinearLayout.LayoutParams(dp(320),-1));body.addView(area,LinearLayout.LayoutParams(0,-1,1f));root.addView(body,LinearLayout.LayoutParams(-1,0,1f));status=tv("  $projectName ready",12f,muted);status.setBackgroundColor(panel2);root.addView(status,LinearLayout.LayoutParams(-1,dp(30)));back.setOnClickListener{if(dirty)confirmLeave{showManager()}else showManager()};add.setOnClickListener{showNewItemDialog(projectName,tree)};refresh.setOnClickListener{refreshTree(tree,projectName)};setContentView(root)}

    private fun saveCurrent(tab:TextView){currentFile?.let{it.writeText(editor?.text?.toString()?:"");pending.remove(it.absolutePath);dirty=false;tab.text="  ${it.name}";status.text="  Saved ${it.name}"}}
    private fun confirmLeave(after:()->Unit){AlertDialog.Builder(this).setTitle("Unsaved changes").setMessage("Save your changes before leaving?").setNegativeButton("Cancel",null).setNeutralButton("Discard"){_,_->dirty=false;after()}.setPositiveButton("Save"){_,_->currentFile?.writeText(editor?.text?.toString()?:"");dirty=false;after()}.show()}

    private fun refreshTree(tree:LinearLayout,projectName:String){if(tree.childCount>1)tree.removeViews(1,tree.childCount-1);renderTree(tree,projectDir(projectName),"",projectName);status.text="  Project refreshed"}
    private fun renderTree(tree:LinearLayout,dir:File,prefix:String,projectName:String){dir.listFiles()?.sortedWith(compareBy({!it.isDirectory},{it.name.lowercase()}))?.forEach{f->val row=tv(prefix+if(f.isDirectory)"📁  ${f.name}" else "📄  ${f.name}",13f);row.setPadding(dp(4),0,0,0);if(f.isDirectory){row.setOnClickListener{if(row.tag==true){row.tag=false;refreshTree(tree,projectName)}else{row.tag=true;renderTree(tree,f,prefix+"    ",projectName)}};row.setOnLongClickListener{showFileActions(f,projectName,tree);true}}else{row.setOnClickListener{openFile(f)};row.setOnLongClickListener{showFileActions(f,projectName,tree);true}};tree.addView(row,LinearLayout.LayoutParams(-1,dp(38)))}}
    private fun openFile(f:File){if(dirty)pending[currentFile?.absolutePath?:""]=editor?.text?.toString()?:"";currentFile=f;val value=pending[f.absolutePath]?:runCatching{f.readText()}.getOrDefault("");editor?.setText(value);editor?.setSelection(editor?.length()?:0);dirty=pending.containsKey(f.absolutePath);status.text="  Opened ${f.name}"}
    private fun showFileActions(f:File,projectName:String,tree:LinearLayout){AlertDialog.Builder(this).setTitle(f.name).setItems(arrayOf("Rename","Delete")){_,which->if(which==0)renameFile(f,projectName,tree)else deleteFile(f,projectName,tree)}.show()}
    private fun renameFile(f:File,projectName:String,tree:LinearLayout){val input=EditText(this).apply{setText(f.name)};AlertDialog.Builder(this).setTitle("Rename").setView(input).setNegativeButton("Cancel",null).setPositiveButton("Rename"){_,_->val n=input.text.toString().trim();if(n.isNotEmpty()&&n!=f.name){val dest=File(f.parentFile,n);if(dest.exists())Toast.makeText(this,"Already exists",Toast.LENGTH_SHORT).show()else if(f.renameTo(dest)){if(currentFile?.absolutePath==f.absolutePath)currentFile=dest;refreshTree(tree,projectName)}}}.show()}
    private fun deleteFile(f:File,projectName:String,tree:LinearLayout){AlertDialog.Builder(this).setTitle("Delete ${f.name}?").setNegativeButton("Cancel",null).setPositiveButton("Delete"){_,_->if(f.deleteRecursively()){if(currentFile?.absolutePath==f.absolutePath){currentFile=null;editor?.setText("");dirty=false};refreshTree(tree,projectName)}}.show()}
    private fun showNewItemDialog(projectName:String,tree:LinearLayout){val input=EditText(this).apply{hint="Name (folders can use /)"};AlertDialog.Builder(this).setTitle("New item").setView(input).setItems(arrayOf("Create file","Create folder")){_,which->val n=input.text.toString().trim();if(n.isEmpty())Toast.makeText(this,"Enter a name",Toast.LENGTH_SHORT).show()else{val f=File(projectDir(projectName),n);if(f.exists())Toast.makeText(this,"Already exists",Toast.LENGTH_SHORT).show()else{if(which==0){f.parentFile?.mkdirs();f.createNewFile()}else f.mkdirs();refreshTree(tree,projectName);Toast.makeText(this,"Created $n",Toast.LENGTH_SHORT).show()}}}.show()}
}
